### ISSUE TITLE
Error while run local or global analysis Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by skbrimer** [ozagordi/shorah#16] opened 2015-09-25 19:34 UTC
Hello, 

I'm having some issues with get ShoRAH to finish a run. I have run it a few times and it comes back with with the local and global analyses and they each return the same error. The error is below:
<pre><code>
 Traceback (most recent call last):
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/dec.py", line 655, in <module>
    main(*args, **vars(options))
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/dec.py", line 561, in main
    (kp, float(proposed[kp][0]) / proposed[kp][1]))
ValueError: could not convert string to float: not found
</pre></code>

I'm not sure what I'm doing wrong, I do not think I am missing a dependency and guidance you could give would be great!

**Comment by ozagordi** [comment] 2015-09-28 07:35
Hi.

No, it's not a dependancy. I don't have all the information here, you should tell me a bit more on the sort of data you are analysing. Do you have enough coverage and diversity? Try also running with a higher alpha and let me know.

**Comment by skbrimer** [comment] 2015-09-28 15:37
Hi Osvaldo,

Sorry about that, I'm working with unpaired ion torrent reads sequencing an avian coronavirus. The genome is ~27.6kbp in length and I have full coverage of the reference genome.  I'm hoping to see if I can determine if there is a sub-population with in our sample due to the high variability of the virus. According to Qualimap's report, which for some reason will not attach, I have an average coverage of 410x +/- 337x (so from 70 to 1000).

I am thinking that the mappers would treat variable regions as errors and they are the lower areas of genome coverage and the conserved regions would be the deeper regions. Is 70x enough to determine the variability in those regions?  

Is there more information that you want/need? I'm sorry if I'm not suppling all that you want I'm much more biologist than bioinformatician. 

I will play with the alpha and let you know how that works as well. 

Thank you for the response, 
Sean

**Comment by skbrimer** [comment] 2015-09-29 19:54
Hi Osvaldo,

I have run a few more tries with adjusting the alpha and the window size. 
<pre>
experiment 1: alpha = 0.2 window = 201 result = failed
experiment 2: alpha = 0.5 window = 201 result = failed
experiment 3: alpha = 1.0 window = 201 result = failed
experiment 4: alpha = 0.2 window = 99 result = failed
experiment 5: alpha = 0.5 window = 99 result = failed
experiment 6: alpha =1.0 window = 99 result = failed
</pre>

I get the same error with each experimnt please see below. 
<pre><code>
Segmentation fault (core dumped)
{0: 44612}
Traceback (most recent call last):
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/shorah.py", line 142, in <module>
    keep_files=options.k, alpha=options.a)
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/dec.py", line 561, in main
    (kp, float(proposed[kp][0]) / proposed[kp][1]))
ValueError: could not convert string to float: not found
</code></pre>
Any ideas?

**Comment by ozagordi** [comment] 2015-09-30 07:39
Hi Sean.
A couple of hypotheses:
1. a combination of low coverage / low diversity in some of the regions of the genome. You expect at least 70, which would be enough to run, but not enough to find low frequency variants. On the other hand you cannot exclude that some regions have much less than 70, maybe zero. I would rather start from a smaller region of interest, maybe a region known to be more variable like, check the coverage there and run giving the `-r` option.
2. There is a limit to the genome size that b2w (a tool inside shorah) can deal with. Same solution as above.

Let me know.
    Osvaldo

**Comment by skbrimer** [comment] 2015-09-30 13:39
Hi Osvaldo,

Thank you for the ideas. I will work on them this afternoon. and Let you
know how it goes. I really appreciate all the help!

Sean

**Comment by skbrimer** [comment] 2015-10-01 14:09
Hi Osvaldo, 
 
I'm having trouble with selecting the region for the analysis, so I'm not able to let you know if it worked or not. I have not been able to figure out a proper format to enter into the region variable. I know the format is chr:start:stop, but when I use the id numbers from my reference(genbank fasta all one chromosome) it kicks back saying it can't find it. I will keep working on it. 

Sean

**Comment by ozagordi** [comment] 2015-10-01 14:44
It should be `-r chr:start-stop`. If you are using genbank ids, you might
have to escape the pipes with backslash, _i.e._ `\|`. You will have to give
a few tries, I guess.

**Comment by ozagordi** [comment] 2015-10-01 14:45
It should be `-r chr:start-stop`. If you are using genbank ids, you might
have to escape the pipes with backslash, _i.e._ `\|`. You will have to give
a few tries, I guess.

**Comment by skbrimer** [comment] 2015-10-01 15:48
Thank you Osvaldo, 
I did need to escape the backslashes. I was able to perform some runs on a couple of different regions and I still got back the error. So I do not think there is anything wrong with the program, I'm thinking that the sample I'm testing it one may be a single sample. It is lab adapted and attenuated strain so maybe we have a clonal isolate. Not was I was expecting but it could be true. 

Right now I'm trying the same parameters on a sample we mix equally, 3 isolates. We will see if it shakes out.  

Thank you for your help!
Sean

**Comment by skbrimer** [comment] 2015-10-01 15:55
Okay, So now I'm stumped. 

This is a screen shot from igv of the mixed control samples: 
![samples1_4](https://cloud.githubusercontent.com/assets/4447895/10225827/22d52bea-682a-11e5-96f5-372525d02264.png)

Sample#3 is the one that I'm testing and it is in fact 3 isolates mixed at equal amounts. You can see the variability on the alignment. I tested just the first 2000bp and I got back the same error 
<pre><code>
Traceback (most recent call last):
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/shorah.py", line 142, in <module>
    keep_files=options.k, alpha=options.a)
  File "/home/sean/shorah/ozagordi-shorah-4507e7e/dec.py", line 561, in main
    (kp, float(proposed[kp][0]) / proposed[kp][1]))
ValueError: could not convert string to float: not found
</pre></code>

This is the parameter that I'm using:
<code>
shorah.py -b ../sample3_map.sorted.bam -f ~/Desktop/templates/Ark_DPI_IBV.fasta -r 'gi\|310696825\|gb\|GQ504720.1\|:10-2000' -a 0.3 -w 99
</code>

Any more thoughts?

**Comment by ozagordi** [comment] 2015-10-01 19:49
Not sure. Some options, they can also be mixed:
1. try an even smaller region;
2. increase alpha by an order of magnitude, if it still fails by another and so on;
3. delete all files before re-running.

**Comment by skbrimer** [comment] 2015-10-06 14:08
Good Afternoon Osvaldo,

I have been playing with the alpha and the region like you suggest still no luck, but I have some other questions if you have time. In your paper you refer to the alpha as the hyper variable but I'm not sure what that actually means. For example I'm currently trying an alpha of 10,000 is that just absurd?

I was looking at some of the freq files before deleting them for the next run and I was wondering is the reference included in the haplotype list, i.e. hapl000? How are the freq files analysed? I imagine that at the end of the script it would concatenate all the windows to give me its best answers but how will I interpret those results?

**Comment by ozagordi** [comment] 2015-10-07 07:31
No, it is not absurd and you can even go higher, depending on the situations.

If you plan on doing global reconstruction, shorah might not be the best performing tool, although one has to keep in mind that global reconstruction is always a though problem. The files you should look at first are the `support.fas` ones. I wrote a [tool](https://github.com/ozagordi/LocalVariants) to analyse these, but it has not been thoroughly tested, so proceed with caution. My suggestion is again to start on a small, even very small region. Possibly a region of size ~ read length, so you can even run `amplian.py` as [described](http://ozagordi.github.io/shorah/local.html). What is your read length?

**Comment by skbrimer** [comment] 2015-10-07 18:18
I'm working with Ion Torrent RNA-Seq data so I have a pretty large range of read lengths. I run from 8 to 450bp with a median of 146bp. I will read the paper and the documentation for your tool and let you know how I fair. Thank you for taking this time ti help. I really do appreciate it.

**Comment by jinlajf** [comment] 2016-02-03 14:49
Hi, 

I have exactly the same problem as skbrimer. I'm trying to run shorah on Ubuntu 14.04, I have a bam file with 11k+ reads aligned to 3.5kbp long reference. Reads are 150bp long with very small variance. I am trying to analyse a small portion of the region with coverage well over 150×. Here is the command I used: 

`shorah.py -b p1_t1_r1.bam -f reference.fasta -w 120 -r "REF_Hu/GII-4/Saga1/2006/JP_AB447456_extraction":1200-1350`

And here is the error I get: 

```
Traceback (most recent call last):
  File "/home/luka/software/shorah-master/shorah.py", line 142, in <module>
    keep_files=options.k, alpha=options.a)
  File "/home/luka/software/shorah-master/dec.py", line 561, in main
    (kp, float(proposed[kp][0]) / proposed[kp][1]))
ValueError: could not convert string to float: not found
```

I tried modifying the dec.py to learn about the value of the 'proposed[kp]' and it turned out to be containing values ('not found', 2085). The respective if sentence (line 560-561) in the dec.pa poses the following condition: 

```
if proposed[kp] != 'not found'
            ph.write('%s\t%f\n' % (kp, float(proposed[kp][0]) / proposed[kp][1]))
```

So clearly the condition does not cover my case. So I changed it to 

```
if 'not found' not in proposed[kp]: #modified this
            ph.write('%s\t%f\n' % (kp, float(proposed[kp][0]) / proposed[kp][1]))

```
Obviously, I have no clue about the implication this change makes. After that the program continued some more and finally crashed with this message: 

```
Reading p1_t1_r1_cor.fas
Output to p1_t1_r1_cor.read
Use of uninitialized value $startpos in addition (+) at /home/luka/software/shorah-master/perllib/ReadUtil.pm line 179.
Use of uninitialized value in concatenation (.) or string at /home/luka/software/shorah-master/fas2read.pl line 24.
readfile read
Started with 0 reads.
Ended with 0 reads.
inputfile = p1_t1_r1_cor.rest
outputfile= p1_t1_r1_cor.geno
Creating up to 200 haplotypes
Permuting up to 50 times
ONEPATH =  True
minimum overlap in graph: 1
No reads in file (or couldn't open file)
ERROR -- can't read p1_t1_r1_cor.geno or .read
Something went wrong in the EM step
```

Obviously, my p1_t1_r1_cor.* files are empty. 

I have tried changing the region in the bam file, and/or changing alpha as suggested previously. 
I am now done with ideas. I would really appreciate if someone could look into this problem. I have no idea if my data is to blame (and how to correct it) or if there's something wrong with the program. I would be happy to provide the bam and fasta file for you to recreate the error and would even appreciate some test files from the shorah team so that I could test the performance of the program and maybe figure out the mistake in my case. It would be great if we could solve this issue. 

Thank you!

**Comment by ozagordi** [comment] 2016-02-08 08:44
Hi.
I guess the easiest now is to provide me with some of your data so that I can try to reproduce the error. Please follow the recommendations [here](http://drive5.com/toy.html) to make a toy example and I will give a look.

**Comment by ozagordi** [comment] 2016-02-09 08:47
I'm closing the issue because it was resolved in a email exchange.

**Closed by ozagordi** 2016-02-09 08:47 UTC
